site_url: https://florianschuttkowski.com
repo_url: https://github.com/flowinho/arc42-website/
copyright: Copyright &copy; 2024 - Florian Schuttkowski
site_name: florianschuttkowski.com
site_author: Florian Schuttkowski
repo_name: flowinho/arc42-website
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/tablesort.min.js
  - javascripts/tablesort.js

theme:
  name: material
  custom_dir: overrides
  language: de
  logo: assets/pixar-me-right-circle.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Zum hellen Modus wechseln

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Farbvorgabe des Systems anwenden

  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
  icon:
      repo: fontawesome/brands/github
      logo: fontawesome/solid/dragon
      tag: 
        default: fontawesome/solid/tag
        mfmkdocs: simple/materialformkdocs
        mermaid: simple/mermaid
        apache: simple/apache
        css: simple/css3
        markdown: simple/markdown
        keys: material/key-chain
        server: material/server
        fonts: material/format-font
        lebenslauf: material/file-account
        glossar: material/library
        kontext: material/arrow-expand-all
        bausteinsicht: material/apps
        ladefuchs: material/ev-station
        swift: material/language-swift
        ios: simple/ios
        uikit: fontawesome/brands/apple
        dersoftwareengineer: fontawesome/solid/laptop-code
        derpapa: material/account-child-outline
        derdatenschutzenthusiast: material/data-matrix
        derpodcaster: material/podcast
        dernerd: material/cards-outline
        derpartner: material/hand-heart
        derblogger: material/keyboard
        git: material/git
        ssh: material/ssh
        github: material/github
        hetzner: simple/hetzner
        cli: fontawesome/solid/terminal
        encryption: material/key-chain
        nextcloud: simple/nextcloud
        ubuntu: material/ubuntu
        python: simple/python
        ruby: simple/ruby

extra:
  tags: 
    MaterialForMKDocs: mfmkdocs
    Mermaid: mermaid
    Apache: apache
    CSS: css
    Markdown: markdown
    PublicKeys: keys
    Server: server
    Fonts: fonts
    Lebenslauf: lebenslauf
    Kontext: kontext
    Glossar: glossar
    Bausteinsicht: bausteinsicht
    Ladefuchs: ladefuchs
    Swift: swift
    UIKit: uikit
    iOS: ios
    Der Software-Engineer: dersoftwareengineer
    Der Papa: derpapa
    Der Datenschutz-Enthusiast: derdatenschutzenthusiast
    Der Podcaster: derpodcaster
    Der Nerd: dernerd
    Der Partner: derpartner
    Der Blogger: derblogger
    GitHub: github
    SSH: ssh
    GIT: git
    Hetzner: hetzner
    CLI: cli
    Encryption: encryption
    Nextcloud: nextcloud
    Ubuntu: ubuntu
    Python: python
    Ruby on Rails: ruby
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/florianschuttkowski/
    - icon: fontawesome/brands/mastodon 
      link: https://chaos.social/@flowinho
    - icon: fontawesome/brands/github
      link: https://github.com/flowinho
    - icon: fontawesome/brands/unsplash
      link: https://unsplash.com/de/@flowinho
    - icon: fontawesome/brands/signal-messenger
      link: https://signal.me/#eu/YYsmjGrYPtnITzp0VY2zv6DvpI0ZO03kGV3ErqrMXQ4Xw1_UJtNI8KqaiDswvKQ
    - icon: fontawesome/solid/envelope
      link: mailto:florian@schuttkowski.com
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/flowinho

plugins:
  - search
  - git-committers:
      repository: flowinho/arc42-website
      branch: main
  - blog:
      pagination: true
      authors_profiles: true
      archive_toc: true
  - rss:
      enabled: true
      use_git: true
      use_material_blog: true
      use_material_social_cards: true
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - tags:
      tags_file: glossar/schlagworte.md
      tags_hierarchy: true
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - privacy:
      links_attr_map:
        target: _blank
  - optimize:
      enabled: true
      cache: false
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: false
  - glightbox
  - awesome-pages
  - typeset
  - meta:
      enabled: true
  - mermaid2:
      arguments:
        securityLevel: 'loose'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  #- pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid_custom
            #format: !!python/name:mermaid2.fence_mermaid # Plain Mermaid, without Material Theme
