name: pipeline
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure auth for Insiders
        run: |
          echo "https://github:${{ secrets.REPO }}@github.com" >> $HOME/.git-credentials
          git config --global credential.helper store
      - name: Configure Git Credentials
        run: |
          git config user.name flowinho
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install git+https://${{ secrets.REPO }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force
